name: network-test


on: 
  workflow_dispatch:

jobs:
  network-test:
    name: Network test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Network test
        id: network-test

        run: |
          echo Running network test...
          npm install
          node index.js
